wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700329627.588535
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      4: 3.11.4
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
epochs:
  desc: null
  value: 50
